name: Build and Push External Repo Docker Image

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v4

      - name: Clone external repo
        run: |
          git clone --depth 1 https://github.com/eko/tado-exporter.git external-repo
          cd external-repo
          git rev-parse HEAD > ../external_latest_commit
          cd ..

      - name: Compare commit hash and skip if no update
        id: check-update
        run: |
          if [ -f last_external_commit ]; then
            if cmp -s last_external_commit external_latest_commit; then
              echo "No update in external repository."
              echo "updated=false" >> $GITHUB_OUTPUT
              exit 0
            fi
          fi
          echo "updated=true" >> $GITHUB_OUTPUT

      - name: Save latest commit hash
        if: steps.check-update.outputs.updated == 'true'
        run: cp external_latest_commit last_external_commit

      - name: Generate date-based tag (YYYYMMDD)
        id: date
        if: steps.check-update.outputs.updated == 'true'
        run: echo "today=$(date -u +%Y%m%d)" >> $GITHUB_OUTPUT

      - name: Load secret
        id: op-load-secret
        if: steps.check-update.outputs.updated == 'true'
        uses: 1password/load-secrets-action@v1
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          DOCKERHUB_TOKEN: op://kubernetes/DockerHub Read Write token/credential

      - name: Copy our Dockerfile
        if: steps.check-update.outputs.updated == 'true'
        run: cp ./Dockerfile ./external-repo/Dockerfile

      - name: Set up QEMU
        if: steps.check-update.outputs.updated == 'true'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: steps.check-update.outputs.updated == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        if: steps.check-update.outputs.updated == 'true'
        uses: docker/login-action@v3
        with:
          username: gyulaasztalos
          password: ${{ steps.op-load-secret.outputs.DOCKERHUB_TOKEN }}

      - name: Build and Push (multi-arch)
        if: steps.check-update.outputs.updated == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./external-repo
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            gyulaasztalos/tado-exporter:latest
            gyulaasztalos/tado-exporter:${{ steps.date.outputs.today }}
